name: documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER: ${{ github.repository }}
        run: |
          REPO="${{ github.repository }}"
          GIT_USERNAME=${REPO%/*}
          GIT_USER=$GIT_USERNAME
          git config --global user.email "$GIT_USERNAME@users.noreply.github.com"
          git config --global user.name "$GIT_USERNAME"
          echo "machine github.com login $GIT_USERNAME password $GITHUB_TOKEN" > ~/.netrc
          if [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy
